### ISSUE TITLE
je n'arrive pas a ajouter une activité dans le cours ou je suis prof 

### ISSUE THREAD

**Issue by plgitlogin** [PlatonOrg/platon#101]
Question je dois créer uen activité avant de pouvoir l'utiliser ?

https://platon.univ-eiffel.fr/courses/98a24003-c571-4831-8aa6-ea8fa733061e/dashboard

**Comment by plgitlogin** [comment]
l'idée c'est que j'utilise le bouton ajouter une activité dans le cours.

**Comment by mciissee** [comment]
https://cisstech.github.io/platon/docs/main/doc/resources/watchers#avantages
