### ISSUE TITLE
Spécifier mon fichier exercice par défaut

### ISSUE THREAD

**Issue by plgitlogin** [PlatonOrg/platon#103]
Je voudrais pouvoir dans mon profile utilisateur spécifier un fichier main.ple qui sera utilisé comme base de remplissage dans le cas d'une création d'exercice (en remplacement de l'exo somme de deux entiers).

**Comment by NewMeeh** [comment]
Fait [ici](https://github.com/PlatonOrg/platon/commit/611f45d5fe24c545a2ee6a8cab4b149a7de89228)

[Documentation](https://platon.univ-eiffel.fr/docs/main/doc/resources/exercises#%C3%A9tape-4--choix-du-mode-d%C3%A9dition)
