### ISSUE TITLE
Disparition de la div ".nextra-nav-container" contenant la navbar avec les différentes pages de la documentation dans la page "Composants"

### ISSUE THREAD

**Issue by xLeay** [PlatonOrg/platon#118]
_La navbar sur la page "Documentation" (elle est pareille sur les autres pages "Introduction" et "Showcase")_

![image](https://github.com/PlatonOrg/platon/assets/92150296/d15ed7a1-ad66-46b6-a7cc-92aaf915d927)

_La navbar sur la page "Composants" (elle est unique sur toute la documentation et ne permet pas de revenir en arrière ou d'effectuer une recherche notamment)_

![image](https://github.com/PlatonOrg/platon/assets/92150296/e26ba4c9-46d7-4edb-b01e-e24533258c47)

**Comment by NewMeeh** [comment]
La page composants est indépendante de la documentation, ce n'est pas quelque chose de prévu dans l'immédiat
