### ISSUE TITLE
Bouton preview visible pour un plo

### ISSUE THREAD

**Issue by nimdanor** [PlatonOrg/platon#119]
Quand on edite les variables d'un plo on doit revenir sur le main.ple pour faire la préview dans le mini menu de la barre des fichiers. 
Peut on avoir le bouton preview visible quand on édite un main.plo.

**Comment by NewMeeh** [comment]
Il y a le bouton visible en bleu, en haut à gauche.

![image](https://github.com/PlatonOrg/platon/assets/77853805/3ce0d460-5a16-4106-942d-c40790d8044e)

**Comment by nimdanor** [comment]
Ok les boutons manquants sont le bouton preview avec la loupe et celui qui lance en full screen.
pour trouver le main.ple normalement c'est juste de remplacer le 'o' à la fin :)

**Comment by nimdanor** [comment]
Ok fermé le bouton "bleu" est ok.
