### ISSUE TITLE
Option "limiter les seed" des activités

### ISSUE THREAD

**Issue by nimdanor** [PlatonOrg/platon#130]
Cette option des activité permet de reduire la dispertion des seed.
On fait random() % 100 ce qui limite les seed a 100 valeurs.

**Comment by Nomehh** [comment]
Cette fonctionnalité existe déjà : 
![image](https://github.com/PlatonOrg/platon/assets/101347535/3c44c2ca-cbf0-45e7-ba6f-bcb2f03e2fa9)

Néanmoins, elle n'est pas claire :
- Par défaut (quand l'option n'est pas cochée), on génère une seed aléatoire entre 0 et 100, et on la "transmet" à tous les exercices -> tous les exercices auront donc la même seed.

- Quand l'option est cochée, on génère une seed aléatoire entre 0 et 100 pour chaque exercice. Tous les exercices auront donc une seed aléatoire comprise entre 0 et 100.

En outre, toutes les seeds sont comprises entre 0 et 100. L'option permet de déterminer si elles seront différentes entre les exercices.

J'apporte des modifications pour mieux expliciter le comportement.

**Comment by nimdanor** [comment]
OK c'est plus clair.
