### ISSUE TITLE
@include ne fonctionne pas sur des fichiers non textuels

### ISSUE THREAD

**Issue by TheValber** [PlatonOrg/platon#131]
On ne peut pas utiliser le @include sur certains types de fichiers.

On a essayé avec **png** et **mp3**, dans les deux cas on obtient l'erreur suivante : 

![image](https://github.com/PlatonOrg/platon/assets/98223161/9a7072d6-1a33-4fce-8722-6b7dd84a1fc1)

**Comment by TheValber** [comment]
Voici le code d'un exercice qui renvoie cette erreur. (peu importe l'exercice, si la première ligne est présente, cela provoque l'erreur)

```py
@include image.png

sandbox = "python"

input = :wc-input-box
input.type = "number"
input.placeholder = "Entrez votre réponse ici"

builder==

==

grader==
grade = 0
feedback["type"] = "error"
feedback["content"] = "Mauvaise réponse"
if input["value"] == 0:
  grade = 100
  feedback["type"] = "success"
  feedback["content"] = "Bonne réponse"
==

title==
ZERO
==

statement ==
Entrez 0 ?
==

form==
{{input}}
==

```

**Comment by NewMeeh** [comment]
Le problème est l'enregistrement des fichiers non textuelles dans les `Sessions`, au moment de la prévisualisation ou du lancement d'un exercice tout les média sont ajoutés aux `variables` de la session. C'est une erreur. 

Il faut rajouter une table qui va gérer les médias, cette table aux un champs `sha256` et un `blob` avec le contenu du fichier. Dans les `variable` de la session on mettra l'`id` du média correspondant.

**Comment by nimdanor** [comment]
Je pense qu'il faut prioritiser cette issue.

**Comment by NewMeeh** [comment]
Dans la version de développement on peut maintenant envoyer des fichiers binaires **mais** il n'est pas possible de les récupérer.
