### ISSUE TITLE
Problème de mise a jour de la date d'ouverture sur Rattrapage

### ISSUE THREAD

**Issue by nimdanor** [PlatonOrg/platon#134]
j'arrive pas a changer la date ..

**Comment by NewMeeh** [comment]
https://github.com/PlatonOrg/platon/assets/77853805/e9738150-6c36-425a-b353-78d3f83f4874

Qu'est-ce qui se passe quand tu essaie de changer la date ?

**Comment by nimdanor** [comment]
ca marce po mais Valentin a déjà corriger le bug.

**Comment by TheValber** [comment]
Le problème est dû au composant nz-range-picker qui était utilisé et ne permettait pas de sélectionner uniquement une date de début ou une date de fin.
Ce problème ne peut plus se produire depuis le commit 135eb39 qui permet de définir uniquement le début ou la fin d'une activité.
