### ISSUE TITLE
On ne peut ajouter seulement des activités que nous avons créé

### ISSUE THREAD

**Issue by NewMeeh** [PlatonOrg/platon#138]
Lorsque l'on ajoute une activité a un cours, on ne peut ajouter que des activité dont nous sommes propriétaires hos on devrait avoir accès à toutes les activités disponibles sur la plateforme, particulièrement celles proposées dans les cercles auxquels on appartiens

**Comment by TheValber** [comment]
Dans la doc de Platon il y a marqué qu'il faut suivre les activités pour pouvoir les ajouter à son cours pour des raisons de performance.


Dans la doc sur les observateurs (https://platon.univ-eiffel.fr/docs/main/doc/resources/watchers) : 

<img width="881" alt="image" src="https://github.com/user-attachments/assets/95673ae5-8812-428b-b72a-fcd9206fbd26">
