### ISSUE TITLE
Statistiques des ressources améliorations

### ISSUE THREAD

**Issue by nimdanor** [PlatonOrg/platon#144]
Il faut que le nombre d'essais soit un float avec 2 chiffres significatifs (et pas un entier).

**Comment by NewMeeh** [comment]
Tu parles de cette stat ?  
![image](https://github.com/PlatonOrg/platon/assets/77853805/d3bfdcd3-f7cb-4a5a-9163-193e7e645e08)

Il faudrait donc aussi le faire ici 
![image](https://github.com/PlatonOrg/platon/assets/77853805/00372769-1e28-45de-85fd-d9d03be94053)

**Comment by nimdanor** [comment]
Oui les deux car c'est trop brutal entre 1,50001 et 2,49999 y a une grosse différence mais cela affiche 2 dans les deux cas.
