### ISSUE TITLE
Page d'acceuil pour les nouveau utilisateurs

### ISSUE THREAD

**Issue by nimdanor** [PlatonOrg/platon#147]
Il faut un bouton supplémentaire sur la page d'acceuil
<Vous n'avez pas de compte sur PLATON>
 qui permet d'afficher la documentation de la première connection.

Cela donne accès a une page de documentation qui explique comment avoir accès à platon.

1) pour les Internes (UGE)
Accès par elearning puis cas. 
2) pour les autres 
Il faut une connection LTI et donc un mail a DR.

**Comment by TheValber** [comment]
Ajouté dans le commit 438a5ba
