### ISSUE TITLE
Bug sur le composant MatchList

### ISSUE THREAD

**Issue by Nathan772** [PlatonOrg/platon#154]
Lorsque l'on utilise le composant "MatchList", il est possible de maintenir le clic de la souris pour relier un point à l'autre.
Une autre méthode existe cependant : celle-ci fonctionne en cliquant sur un premier point, puis cliquer sur le second point que auquel on veut relier le premier. Le problème survient lorsqu'on utilise la deuxième méthode : il n'est possible de l'utiliser qu'une seule fois, après qu'on il est seulement possible des relier des points en maintenant le clique.

**Comment by TheValber** [comment]
Il reste un problème avec ce composant dans le cas suivant : 

Si on relie deux points avec des clics, on ne peut plus lier le point de source avec d'autres en glissant la souris.
Si on supprime le lien, le point de source peut à nouveau être lié en glissant la souris.
