### ISSUE TITLE
Problème avec l'interface d'edition de PLA

### ISSUE THREAD

**Issue by nimdanor** [PlatonOrg/platon#173]
je prend un exo et quand j'essaye de le placer dans un groupe il m'ouvre l'exo en mode ressource....
je fait back mais je perd ce que j'ai pas sauvegardé ce qui est agaçant
Deux trucs :
-  il ne devrait pas pouvoir remplacer la page courrant sans me dire qu'il y a quelque chose a sauvegarder avant de partir ...
- il ne devrait pas partir quand je place "mal" l'exo dans le groupe.

Mathieu dit moi quand je peux te faire une démo de mes problèmes avec l'interface.

**Comment by Nomehh** [comment]
## Reproduction : 
Avoir des exercices non sauvegardés dans un groupe de son activité, puis cliquer sur le **TITRE** d'un exercice dans la liste des exercices proposés (les cartes présentes dans les groupes ne sont pas cliquables).

## Solutions : 

1. Afficher un message d'alerte si on tente de quitter la page sans avoir sauvegardé.
2. Ouvrir la ressource devrait se faire dans une autre page.
3. Ne pas rendre les titres cliquables, car c'est ergonomiquement incompatible. Cette fonctionnalité devrait être déplacée, ce qui nous offre plusieurs choix :

   - Ajouter un bouton.
   - Rendre le logo "Exercice" cliquable.
   - Ouvrir la ressource uniquement avec un clic molette.
   - Modifier le bouton "Éditer" pour qu'il redirige vers la page de la ressource (ce qui serait dommage).
   
![image](https://github.com/user-attachments/assets/99aaa770-7bbd-4613-aff2-f4cec65c44fc)

Si j'ai raté quelque chose, n'hésitez pas à me le notifier ici. Autrement nous pourrons nous voir _lundi 23/09 après 9h30_.

**Comment by nimdanor** [comment]
je pense que j'ai un problème de cache. ... 
je n'arrive pas a avoir le problème que j'avais Hier.
IL faut que l'on règle ce problème avec les mise a jour.

**Comment by Nomehh** [comment]
C'est possible, j'ai ouvert l'issue #166 a ce propos. 
J'ai également vu avec Mamadou, qui m'a proposé des solutions. 
Nous en discuterons avec @NewMeeh.

**Comment by nimdanor** [comment]
good

**Comment by Nomehh** [comment]
Après avoir reproduit le bug, j'ai effectué des modifications pour obtenir le comportement suivant :

Dès qu'on commence à drag, le titre devient non cliquable. Cependant, si on ne fait pas de drag, le comportement par défaut est conservé. Le comportement de base a également été ajusté pour ouvrir la ressource dans une nouvelle page.

**Comment by nimdanor** [comment]
excellent il faut programmer une mise a jour.
