### ISSUE TITLE
SortList Elements centrés

### ISSUE THREAD

**Issue by nimdanor** [PlatonOrg/platon#176]
Pour faire un exercice de réorganisation du code avec sorlist il faut pouvoir indiquer que l'on veut respecter l'indentation.
Et donc que les textes ne soient pas centrée dans les div.

Comment fait on ? 

https://platon.univ-eiffel.fr/editor/9bd9e568-200f-4eaf-a1e3-51dcb1933abb?version=latest

**Comment by Nomehh** [comment]
La **SortList** possède un champ `alignment` que vous pouvez définir sur la valeur `"left"` afin d'aligner les éléments à gauche, bien que cela ne soit peut-être pas nécessaire dans votre cas.

De plus, dans le champ `content` de chaque élément, vous pouvez utiliser du **markdown**, ce qui peut être utile pour gérer l'indentation.

![image](https://github.com/user-attachments/assets/41306977-def2-4f6f-8597-d2902615bb88)

Il est également possible d'ajouter une spécification de langage, comme sur Discord (comme je l'ai fait ici dans le champ `content` de l'item 0), en ajoutant par exemple `"py"` pour le Python. Cela permettrait d'afficher la coloration syntaxique. Cependant, il semble que le comportement par défaut de ce composant pour la coloration soit actuellement buggé.

**Comment by nimdanor** [comment]
Formidable mais le template que j'ai ne propose pas de modifier ce champs ....
