### ISSUE TITLE
Liens de DEMO

### ISSUE THREAD

**Issue by nimdanor** [PlatonOrg/platon#18]
On a besoin d'un l"ien de démo" comme sur pl pour plusieurs usages:
- exemple dans la doc 
- showcase sur des sites web
- éléments dans un cours 

On peut utiliser la Prévisualisation sur une version fixé de la ressource (ou bien latest).

Ceci est en plus de cours de démo.

**Comment by nimdanor** [comment]
Cela peut marcher aussi sur une ressource qui ne marche pas, l'idée est que dans la doc on donne un exemple de message d'erreur en fournissant un lien de démo sur une ressource casée.

**Comment by NewMeeh** [comment]
Disponible sur les exercices et les activités (Bouton partager sur la vue d'ensemble de la ressource) 

![Capture d’écran 2024-06-07 à 09 52 20](https://github.com/PlatonOrg/platon/assets/77853805/723f4e91-8424-4f9d-a6c3-f2b8acb99e9f)
