### ISSUE TITLE
Resizable CodeEditor

### ISSUE THREAD

**Issue by DenisB2** [PlatonOrg/platon#194]
Bonjour,
Sauf erreur de ma part, il n'y a qu'un seul composant Editeur de code dans Platon.
Habitué à d'autres environnements, je trouve gênant que chaque élève ne puisse pas choisir le nb de lignes qu'il souhaite voir dans cet éditeur (ça dépend grandement de la taille d'écran dont on dipose, et aussi des goûts de chacun).
Serait-il possible d'ajouter une poignée de changement de taille en bas à droite (comme pour l'éditeur dans lequel je tape ce message par exemple) ?
Ou sinon, la possibilité de paramétrer le nb de lignes visibles ?
Merci.

**Comment by Nomehh** [comment]
Bonjour,

Merci pour votre retour !

**Oui**, il est tout à fait possible pour nous d'ajouter une fonctionnalité permettant de contrôler la taille de l'éditeur directement depuis celui-ci. Cependant, cette fonctionnalité n'existe pas encore pour le moment.

Actuellement, la hauteur de l'éditeur est paramétrable par le professeur via le champ `height`, qui prend une valeur en pixels. Toutefois, comme vous l'avez mentionné, ce paramètre étant spécifique à chaque utilisateur, il devrait également être configurable par les élèves.

**Comment by nimdanor** [comment]
Je pense qu' editeur est resizable il suffit de prendre le coin en bas a gauche et de le déplacer !!!

je ne comprend pas l'isssue.

**Comment by nborie** [comment]
Ce n'était pas le cas quand l'issue a été écrite. L'option a été faite récemment et déployée rapidement. C'est pas complètement tombé du ciel, les jeunes ont bossés (mais ils n'avaient pas fermé l'issue). L'issue a bien suivi son cycle naturel.

**Comment by nimdanor** [comment]
L'issue a bien suivi son cycle naturel.
Sauf que j'ai perdu mon temps.
Donc il faut fermer les issues. 
Normalement il faut indiquer dans le log de la version que l'on corrige une issue et comme cela elle est fermée automatiquement ou je me trompe ?

**Comment by NewMeeh** [comment]
Pas la peine de l'indiquer dans les logs de version, je l'avais référencée dans un commit. J'aurais dû la fermer à ce moment là, autant pour moi.
