### ISSUE TITLE
Bouton terminer

### ISSUE THREAD

**Issue by nimdanor** [PlatonOrg/platon#202]
Je n'ai toujours pas moyen de débloquer les étudiants qui ont "terminer" leur activité par erreur.

**Comment by NewMeeh** [comment]
Pour l'instant il a été décider de ne plus permettre aux élèves de terminer leurs activité par eux même, l'enseignant aura la possibilité de fermer l'activité pour tout les élèves. On ajoutera ensuite une interface pour permettre aux enseignant un contrôle plus fin sur chaque élève. Voir https://github.com/PlatonOrg/platon/issues/191

**Comment by nimdanor** [comment]
Mon problème est que j’ai plein d’élèves qui ont perdu la première activité.

**Comment by nimdanor** [comment]
Oui c’est nécessaire.

**Comment by nborie** [comment]
Je pense que les pour les fiches de TP ou de révisions standard, le bouton terminer n'est ni intuitif, ni adapté en effet. Coté utilisateur, quelque soit les promos, tout le monde se fait avoir. Un bouton ré ouvrir permet de patcher mais par défault, je ne sais pas si on a envie de terminer ces activités un peu autonomes.

![Capture d’écran du 2024-10-20 21-30-31](https://github.com/user-attachments/assets/fd2b29d8-81f3-445b-a324-8a031c51efc2)
