### ISSUE TITLE
Composant cloze

### ISSUE THREAD

**Issue by nimdanor** [PlatonOrg/platon#208]
un input pour faire des questions cloze.
Avec l'affichage de l'input a la place du mot manquant. 

Un énoncé Cloze:  
"Remplir les {} manquant. C'est {=amusant#Rétroaction pour la bonne réponse~=excitant#Rétrocacyion} !"

Chaque mot manquant produit un composant suplémentaire, les composants input créés sont numéroté dans l'ordre.

Format Cloze 
https://docs.moodle.org/4x/fr/Question_cloze_%C3%A0_r%C3%A9ponses_int%C3%A9gr%C3%A9es

**Comment by nimdanor** [comment]
IL faut une largeur minimale pour que l'utilisateur click dessus avant que la taille s'adapte. Non ?

**Comment by Nomehh** [comment]
> IL faut une largeur minimale pour que l'utilisateur click dessus avant que la taille s'adapte. Non ?

Oui, elle est de 64 pixels par défaut (taille minimal).

**Comment by nimdanor** [comment]
Voici un exemple de ce que je veux 
<img width="1828" height="740" alt="Image" src="https://github.com/user-attachments/assets/8457c08d-8eec-4aca-a67e-ba475b346ba8" />
