### ISSUE TITLE
Variables suplémentaires dans un exercice

### ISSUE THREAD

**Issue by nimdanor** [PlatonOrg/platon#21]
j'ai l'impression que le variables d'exercices voire image ne fonctionnent pas.
![image](https://github.com/PlatonOrg/platon/assets/10084549/127d44e3-034b-410c-88f1-116cebc7fb26)

**Comment by nimdanor** [comment]
Pour accèder c'est le bouton editer a droite de l'exercice.

**Comment by NewMeeh** [comment]
Le format attendu pour modifier les variables est un json. 

Pour cet exemple il faudrait utiliser le code suivant :
```json
{
    "z3" : 1
}
```

**Comment by nimdanor** [comment]
Très bien mais alors le module de modification de variables par formulaire doit être utilisé à cet emplacement en lieux et place de l'editeur json qui est quand même sélectif pour les utilisateurs.
