### ISSUE TITLE
Customisation du composant WordSelector

### ISSUE THREAD

**Issue by nborie** [PlatonOrg/platon#228]
Bonjour,

Suite à des premiers prototypes avec le composant WordSelector, deux problèmes d'ergonomie sont apparus rapidement :

 * Besoin de pouvoir changer / adapter la taille (la largeur `width` surtout) du composant.
 * Avoir des tailles de bulles pour les mots de manière à ce que les mots ne soit pas coupé au milieu car trop long.
  
Mis à part ces deux détails d'ergonomie, la sélection par clic et le réordonnement par cliquer-glisser dans la phrase fonctionne très bien.  
  
![Capture d’écran du 2024-11-25 09-48-52](https://github.com/user-attachments/assets/113a6fbf-9b29-40ff-bc32-3d95f13cf688)

Sur le screenshot, on pourrait augmenter la largeur du composant mais aussi augmenter la largeur des bulles pour les mots pour éviter de couper les mots `mechanical` et `engineering`.

Le lien suivant devrait permettre de tester un peu tout cela : https://platon.univ-eiffel.fr/player/preview/767cf366-1f0d-43f9-a195-f8fb95f4a90c?version=latest

Bon courage.

**Comment by nimdanor** [comment]
En même temps si il y a changement de ce composant, il faut ajouter la possibilité de drag & drops les mots de la section du bas vers celle du haut.
IL est vrai que clicker sur les mots est rapide et marche bien.
Mais des fois on voudrais aussi pouvoir faire drag & drop (au bon endrois entre les mots déjà présent).
Sinon la façon efficace est de clicker sur le mots dans l'ordre ;)
