### ISSUE TITLE
elif not a python keyword in editor

### ISSUE THREAD

**Issue by nimdanor** [PlatonOrg/platon#230]

**Comment by NewMeeh** [comment]
Ça fonctionne de mon côté : 
<img width="447" alt="image" src="https://github.com/user-attachments/assets/88a4abc8-27a8-4d0d-b58e-4d397c0151fa">

Peux-tu réessayer et m'envoyer un screen si l'erreur se reproduit ?

**Comment by Nomehh** [comment]
Pour avoir la coloration syntaxique il faut bien préciser le [shebang](https://fr.wikipedia.org/wiki/Shebang) en haut des balises.

Ici c'est `#!lang=py` pour la coloration syntaxique de python.
