### ISSUE TITLE
Bug composant MathLive

### ISSUE THREAD

**Issue by ddoyen** [PlatonOrg/platon#231]
Le clavier virtuel n'apparaît plus (quand on clique sur l'icône) dans mes exercices utilisant le composant MathLive.

J'ai testé uniquement avec firefox. Mais dans la doc des composants, le composant MathLive interactif fonctionne bien : le clavier apparaît. Donc j'ai tendance à penser que ce n'est pas le navigateur le problème.

**Comment by NewMeeh** [comment]
![image](https://github.com/user-attachments/assets/babaa1ff-4707-4baf-b78b-e37eaf0b140c)
La preview fonctionne dans une iframe ce qui pose problème pour afficher le clavier de MathLive, ce problème n'existe pas une fois l'activité proposé aux étudiants car ce n'est pas dans une iframe à ce moment là. 
Comme solution temporaire pour tester les exercices il faut les ouvrir dans un nouvel onglet via le bouton montré dans le screen.

**Comment by NewMeeh** [comment]
C'est réglé, ce sera ajouté dans la prochaine mise à jour (probablement jeudi au plus tard)
