### ISSUE TITLE
IL n'y a pas d'indicateur de fonctionnalité sur le mode de navigation

### ISSUE THREAD

**Issue by nimdanor** [PlatonOrg/platon#232]
Sur les autre éléments des parametres d'une activité il y a un ? avecc un opup qui permet de comprendre son choix ;)

**Comment by NewMeeh** [comment]
<img width="544" alt="image" src="https://github.com/user-attachments/assets/097e5308-8b8c-4f32-885f-e2d1bba9081b">

Les `?` sont affichés dans le menu déroulant.

**Comment by nimdanor** [comment]
C'est malin et c'est malin !
Mais alors pour les vieux suivez mon regard un ? pour dire que chaque choix a son ? mais qu'ils sont bien cachés : 
![image](https://github.com/user-attachments/assets/4cac5aa4-e07e-4f36-a2c3-97c6bb96b0d6)

Pourquoi ils n'apparaisent pas quand il est selectionnée ...

**Comment by NewMeeh** [comment]
<img width="546" alt="image" src="https://github.com/user-attachments/assets/3b9c8cff-69d8-4936-b3ec-0d9beb5983fc">
Dorénavant ce sera affiché même quand le mode est sélectionné
