### ISSUE TITLE
Le texte introduction d'une activité est centré !!

### ISSUE THREAD

**Issue by nimdanor** [PlatonOrg/platon#234]
Ce n'est pas toujours ce que l'on veux .... 
Pourquoi TOUT est centré ??
Peut on avoir le justification a gauche comme partout ailleurs. 

Merci

**Comment by Nomehh** [comment]
Par défaut, ca ne sera plus centré, si vous souhaitez centrer votre texte vous pouvez toujours utiliser les balises
```html
 <center> votre texte centré ici </center>
``` 
Le champs introduction supportant la syntax markdown.
