### ISSUE TITLE
Petite amélioration sur les statistiques ressources dans le supermarché PLaTon

### ISSUE THREAD

**Issue by nborie** [PlatonOrg/platon#239]
Après un peu d'expérience (bientôt 1 an d'utilisation...), il apparaît que les deux stats (maintenant bien calculées, sans lag et de manière feignante...)  sur chaque ressource, c'est super pratique, visuellement sympa et ça donne bien de l'information sur la ressource. Toutefois, ça affiche pas les deux stats les plus parlantes. 

Actuellement, ça affiche (le pourcentage d'apprenants ayant eu 100 sur 100 ) et ensuite le nombre de fois que l'exo a été traité.

Il faudrait remplacer ça par : (la note moyenne des apprenants en pourcentages) et ensuite le nombre de fois que l'exo a été traité.

AVANT : 0% de réussite pour 102 utilisations
AVEC CETTE ISSUE : Note moyenne de 44% pour 102 utilisations

Cette nécessité vient de deux facteurs sur nos données pédagogiques portées par les exos : *
 * D'une part, de plus en plus d'exercices utilisent toute l'échelle de note et ne sont pas en mode 0 (échec) ou 100 (réussite).
 * D'autre part, les activités, qui portent plein plein plein d'exos ont quasiment toute 0% de réussite car même si elle peuvent avoir 18/20 de moyenne, personne ne peut one-shotter à 100/100 une dizaine d'exercice d'affilé.
 
 Ainsi, la note moyenne (car on a le droit de se tromper) sera à la fois plus parlante sur les exos et plus parlante sur les activités que la réussite moyenne à 100/100. Je joins des petites images du C et du Système, on a l'impression que les activités beaucoup jouées sont toutes infaisables mais les notes moyennes peuvent être très bonnes. 
 
 
![Capture d’écran du 2024-12-13 11-25-15](https://github.com/user-attachments/assets/911a4221-73d2-4580-ad7c-ca6ceabed9ab)

![Capture d’écran du 2024-12-13 11-38-07](https://github.com/user-attachments/assets/c12215eb-b3a8-4456-a070-523a931ed81f)

**Comment by NewMeeh** [comment]
Voici à quoi ça ressemble une fois la modification effectuée :) 

<img width="836" alt="image" src="https://github.com/user-attachments/assets/0e98db96-3700-4872-8b52-45cc92aff1a0" />

<img width="832" alt="image" src="https://github.com/user-attachments/assets/be96c2fb-9f97-4b11-9266-814bd9e18be9" />

**Comment by nborie** [comment]
Nickel.
C'est un petit fix mais c'est un pas sympathique d'ergonomie.
