### ISSUE TITLE
Cours Options Front Tabulations paramètres problem

### ISSUE THREAD

**Issue by Ofghanirre** [PlatonOrg/platon#25]
Quand on se situe dans la page des cours, et qu'on va dans l'onglet Paramètres, on accède à une interface fournissant 2 options:
Informations produit un affichage normal
![image](https://github.com/PlatonOrg/platon/assets/18609818/81aa531b-6204-4d16-bc06-c7c3d33a95d0)
Demo produit un affichage qui donne l'impression que nous ne sommes plus dans l'onglet paramètres
![image](https://github.com/PlatonOrg/platon/assets/18609818/e8530845-8b54-4ee1-90e0-d045ddb3f0f9)

À corriger

**Comment by osmocode** [comment]
Fixed on [commit](https://github.com/PlatonOrg/platon/commit/09fb612ed7f8c9c3f306dcfaf5f2c2543968744f)
