### ISSUE TITLE
l'accès aux cercles

### ISSUE THREAD

**Issue by nimdanor** [PlatonOrg/platon#27]
l'accès aux cercle n'est pas géré, il faut que les droits soit mis en place.

Règles d'accès : 
-> on a accès en lecture et en utilisations (import/extends) aux cercles supérieurs (platon est le cercle le plus haut). 
-> on à accès en écriture sur : son propre cercle et les cercles dont on est membre.
-> on à accès en lecture aux cercle qui sont parent des cercles dont on est membre.

Règles d'appartenance : 
-> On devient membre d'un cercle quand on a été invité par un membre.
-> Quand on se connecte la première fois en temps qu'éditeur de ressource (connexion enseignant de  LTI par exemple) on doit choisir le cercle dans lequel on souhaite être intégré pour cela deux méthodes si le LTI a fourni une information -> utiliser l'information, Sinon demander à l'utilisateur de choisir la discipline et le thème du cours.

Exemple:
David se connecte et précise qu'il est intéressé par la création d'un cour d'algèbre en L1-Math. 

Le cercle n'est pas ouvert il sera membre une fois invité une notification est envoyée au membre du cercle responsable des invitations (par défaut le propriétaire, par défaut l'administrateur Ypicker). 

David a un cercle personnel qui est en algèbre.
Il est donc membre du cercle algèbre (une fois invité).
David est membre du cercle python (il a fait une demande et a été invité).

Il a donc accès  en lecture à : Platon, Maths, algèbre, Informatique, Python, son cercle.
Accès en écriture à : Algèbre, Python et son cercle.

**Comment by mciissee** [comment]
Déjà fait : https://cisstech.github.io/platon/docs/main/doc/resources/permissions
