### ISSUE TITLE
Éditeur par formulaire

### ISSUE THREAD

**Issue by nimdanor** [PlatonOrg/platon#28]
Il nous faut un un éditeur par formulaire de variables d'exercice !
pour plusieurs Use cases !
Complétion de modèle et modification des paramètres  d'exercice ou d'activité.

Ou en est on au sujet de formly ??
Est il intégrable ?

**Comment by NewMeeh** [comment]
Nous allons développer une première version sans formly car nous voulons générer le formulaire dynamiquement et Formly ne semble pas adapté pour cela.

**Comment by mciissee** [comment]
Déjà fait : https://cisstech.github.io/platon/docs/main/doc/programing/exercise/config
