### ISSUE TITLE
Vérifier les rôles LTI tests fonctionnels

### ISSUE THREAD

**Issue by NewMeeh** [PlatonOrg/platon#37]
Faire un document validant l'usage des différents rôles sur PLaTon il faut inscrire les utilisateur via Moodle avec tout les rôles possibles sur Moodle puis voir si c'est bien transféré sur platon.

**Comment by NewMeeh** [comment]
Faire un document par rôle avec pour objectif de remonter des issues sur ce qui est contre intuitif ou non fonctionnel ceci est un travail CRITIQUE

**Comment by osmocode** [comment]
The connection errors were not related to the roles but to the encoding of the roles. Problem fixed on #48 !
