### ISSUE TITLE
Composant feedback pour la gestion des résultats doctest

### ISSUE THREAD

**Issue by nimdanor** [PlatonOrg/platon#51]
le html de l'exercice Testdebasedepltest2023 est KC
il faut lancer l'exercice et valider le contenu de l'exercice pour voir  le problème 

je ne pense pas qu'il faille ECRIRE un composant feedback 
qui utilise le type et le content pour afficher quelque chose de joli.

**Comment by nimdanor** [comment]
Dans pl il y a un fichier feedback2023.py qui contient une classe de gestion des résultats de doctest.
Yggdrasil/AAAA/dominique/python/template/feedback2023.py
typiquement 

si feedback = { "type":"pltest", "content": currentfeedback.toJson() } 
alors on aurais dans le composant angular Feedback une interprétation de cela d'une façon proche des celle qui est faites 
dans PL pour les exos PL.

**Comment by NewMeeh** [comment]
Pour l'instant ça fonctionne bien avec quelques modifications sur le template.html de cette façon ça fonctionne de la même manière que sur premier langage. La seule modification dans le template est l'utilisation du markdown de la librairie https://github.com/cisstech/nge.

**Comment by NewMeeh** [comment]
Le composant est disponible [ici](https://platon.univ-eiffel.fr/docs/components/widgets/wc-foldable-feedback)
