### ISSUE TITLE
Modifications vue élève sur PLaTon

### ISSUE THREAD

**Issue by NewMeeh** [PlatonOrg/platon#52]
Modifications à faire en front-end : 
 
 - Un élève ne devrait pas avoir accès la modification du nom d'un cours 

![Image](https://user-images.githubusercontent.com/77853805/254915969-053d1a35-ce51-4e98-bb6b-0f38c83a229b.png)

 - Un élève ne devrait avoir accès à la modification de la description d'un cours

![Image](https://user-images.githubusercontent.com/77853805/254916391-50c02f4a-b980-4df8-9c20-72c3bb0e9884.png)

 - Un élève ne devrait pas avoir accès à la modification du titre des sections 

![Image](https://user-images.githubusercontent.com/77853805/254916650-1f69066c-dc53-409b-89fa-09b3e8e5d5f8.png)

- pas de modification de l'ordre des section ou d'insertion non plus 

![Image](https://user-images.githubusercontent.com/77853805/254916901-e6fadd99-a5b0-4421-b29a-59059300676e.png)

- Pas d'ajout d'activité dans un cours non plus 

![Image](https://user-images.githubusercontent.com/77853805/254917085-fe1e44af-44c1-482a-8634-4cc03d4f6bd2.png)

- Un étudiant ne devrait pas voir l'onglet "Paramètres" d'un cours 

![Image](https://user-images.githubusercontent.com/77853805/254917382-0b20d168-edc1-40b3-acc2-de0e02c0e987.png)

**Comment by osmocode** [comment]
Fix present on [commit](https://github.com/PlatonOrg/platon/commit/ecdd987babc895a7142de916522ac8645c8eed79)
