### ISSUE TITLE
Modification back élève sur PLaTon

### ISSUE THREAD

**Issue by NewMeeh** [PlatonOrg/platon#53]
Cet issue fait suite à l'issue #52, c'est modifications sont à faire en back-end : 

 - Un élève ne devrait pas pouvoir manipuler les sections ajout, modification, suppression

**Comment by osmocode** [comment]
Fix presente on [commit](https://github.com/PlatonOrg/platon/commit/ecdd987babc895a7142de916522ac8645c8eed79)
