### ISSUE TITLE
Faire une sous route dans les paramètres des ressources

### ISSUE THREAD

**Issue by NewMeeh** [PlatonOrg/platon#54]
![Image](https://user-images.githubusercontent.com/77853805/254925980-9ed3e4c0-ce93-44c4-81ac-0b6b2d21f252.png)

Remplacer l'url `https://localhost/resources/d802eeaa-948f-4202-9b53-8f2b1173240b/settings?tab=informations` par quelque chose comme suit `https://localhost/resources/d802eeaa-948f-4202-9b53-8f2b1173240b/settings/informations`

Sinon possibilité d'état incohérent comme dans le screenshot

**Comment by osmocode** [comment]
Fix present on [merge commit](https://github.com/PlatonOrg/platon/commit/ecdd987babc895a7142de916522ac8645c8eed79)
