### ISSUE TITLE
Exercices : Un score égal à -1 consomme une tentative

### ISSUE THREAD

**Issue by ddoyen** [PlatonOrg/platon#56]
Je signale un petit bug. Quand on renvoie un score égal à -1 dans un exercice (erreur de saisie), cela compte comme une tentative. Ce n'est pas le comportement souhaité, cela ne devrait pas consommer de tentative.

**Comment by NewMeeh** [comment]
Merci pour cette issue, en effet ce n'est pas le comportement souhaité. Ce problème à été réglé et sera déployée dès ce soir.
