### ISSUE TITLE
Components : graphiques

### ISSUE THREAD

**Issue by NewMeeh** [PlatonOrg/platon#57]
Il faut remettre les composants `chart-viewer-bars`, `chart-viewer-pies` et `chart-viewer-radar` 
Il faut les mettre a jour afin qu'ils utilisent la librairie `echarts`

**Comment by Ofghanirre** [comment]
Je suis dessus
Composants Pie / Bars réalisés, fonctionnels sur la documentation mais bugs sur des exercices PLaTon, en cours de traitement
