### ISSUE TITLE
Yggdrasil: how to indicate a multi-try exercice

### ISSUE THREAD

**Issue by nimdanor** [PlatonOrg/platon#65]
Is there a way to indicate that the exercice can be tryed multiple times.

Can we set a maximum number of trys ?

**Comment by mciissee** [comment]
https://cisstech.github.io/platon/docs/main/doc/programing/activity/config#définissez-les-actions-

**Comment by nimdanor** [comment]
I have found the parameter. my appologies for the ticket.
