### ISSUE TITLE
Quand on créé une activité avec le mode de navigation "Dynamique", cela ne fonctionne pas.

### ISSUE THREAD

**Issue by TheValber** [PlatonOrg/platon#71]
Bug 1 : Avec le mode "Dynamique", à la validation du premier exercice, on obtient l'erreur : `This exercise is not the most recents opened, please reload your page.`

Bug 2 : Après avoir eu cette erreur, la sélection de l'un des modes au hasard ne fonctionne plus dans l'éditeur de l'activité. Quand on le sélectionne, cela considère que le fichier main.pla n'a pas été modifié et on ne peut pas l’enregistrer et donc pas sélectionner ce mode. (Les deux autres fonctionnent encore). Redémarrer l'éditeur de l'activité permet d'avoir à nouveau accès aux trois modes (toujours avec le Bug 1)

**Comment by NewMeeh** [comment]
Cette feature a été retirée #86, dans l'attente d'un développement plus complet de la feature.

**Comment by NewMeeh** [comment]
Ce mode est maintenant appelé `Intelligent` ou `Next` f4638e95056d2019cd432cae25f9b17184564ebb
