### ISSUE TITLE
Ajouter un bouton "Exercice suivant" dans une activité en mode de navigation "Manuel".

### ISSUE THREAD

**Issue by TheValber** [PlatonOrg/platon#72]
Dans une activité en mode de navigation "Manuel", rajouter un bouton "Exercice suivant" qui s'affiche quand on complète un exercice. Cela serait plus ergonomique et compréhensible que de cliquer dans le sommaire.

**Comment by nimdanor** [comment]
The problem:
en mode manual there is no visible ways to go to the next exercise when the current one is done.

Proposition : 
The validate button must be transformed in a Next (suivant) button that go to the next exercise in the activity/

**Comment by NewMeeh** [comment]
fixed #86
