### ISSUE TITLE
[feature] a way to see the readme file not download it

### ISSUE THREAD

**Issue by nimdanor** [PlatonOrg/platon#79]
It the theories  
when using @copycontent readme.md the file is download.

Let's have a @ showcontent readme.md 
that create a popup or a new tab
that show the readme.md converted to html.

**Comment by NewMeeh** [comment]
We now have a preview for some files, you can easily see [here](https://github.com/PlatonOrg/platon/blob/main/libs/shared/ui/src/file-preview/file-preview.ts) the supported extensions.
The user always gets a preview but can download if he wants. 
![image](https://github.com/PlatonOrg/platon/assets/77853805/b572b88d-5ac8-47fa-a273-357889a58760)
