### ISSUE TITLE
Avec le composant Automaton-editor, quand on valide l'exercice les transitions disparaissent de l'affichage

### ISSUE THREAD

**Issue by TheValber** [PlatonOrg/platon#81]
Avec le composant Automaton-editor, quand on valide l'exercice les transitions disparaissent de l'affichage mais les états restent. Cela n'impacte que l'affichage, les transitions sont accessibles dans le grader.

**Exemples d'affichage :**

Avant de finir l'exercice :

![image](https://github.com/PlatonOrg/platon/assets/98223161/7de87147-9d05-421b-aa25-dc69d59c5601)

Après avoir validé :

![image](https://github.com/PlatonOrg/platon/assets/98223161/b75083b1-41c3-4db6-9526-3dda39ea0e73)

**Comment by NewMeeh** [comment]
fixed #86
